### ISSUE TITLE
Phpparser stubs

### ISSUE THREAD

**Issue by staabm** [phpstan/phpstan-php-parser#12]
Since PhpParser only provides very simple phpdoc typing and nikic seems to no want to merge phpdoc adding PRs (see e.g. https://github.com/nikic/PHP-Parser/pull/647) wouldn‘t it make sense to add a stub file into this repo which adds further typing information?

examples for such phpdoc cannbe found in https://github.com/nikic/PHP-Parser/pull/647/files

wdyt?

**Comment by JanTvrdik** [comment]
I don't understand. Why should parser library provide stubs for some other library?

**Comment by ondrejmirtes** [comment]
Of course, feel free to contribute them :)
